parameters:
- name: repository
  type: string
- name: dockerfile
  default: '**/Dockerfile'
- name: buildContext
  default: '.'
- name: containerRegistry
  default: 'cgr-sqp'

jobs:
- job: build
  variables:
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}: # trigger by tag
      tags: |
        $(Build.SourceBranchName)
        latest
      buildName: $(Build.SourceBranchName)
    ${{ elseif eq(variables['Build.Reason'], 'PullRequest') }}: # trigger on PR
      tags: $(Build.BuildId)-pr
      buildName: $(Build.BuildId)-pr
    ${{ else }}:
      tags: |
        $(Build.BuildId)-unstable
      buildName: $(Build.BuildId)-unstable
  steps:
  - script: |
      echo "##vso[build.updatebuildnumber]$(buildName)"
    displayName: Update build name

  - task: Docker@2
    displayName: Login to SQP container registry
    inputs:
      containerRegistry: ${{ parameters.containerRegistry }}
      command: login

  - task: NuGetAuthenticate@1
    displayName: Authenticate to NuGet

  - task: Docker@2
    displayName: Build Docker image
    inputs:
      containerRegistry: 
      repository: ${{ parameters.repository }}
      command: build
      DockerFile: ${{ parameters.dockerFile }}
      buildContext: ${{ parameters.buildContext }}
      tags: $(tags)

  - task: Docker@2
    displayName: Push Docker image
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      containerRegistry: ${{ parameters.containerRegistry }}
      repository: ${{ parameters.repository }}
      command: push
      tags: $(tags)

